import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Radar, LayoutDashboard, BriefcaseBusiness, Database, BookOpen, ArrowUpRight, ChevronDown, Search, Download, ArrowRight, SlidersHorizontal, Check, Clock3, CircleAlert, Globe2, Github, X, ScanLine, Layers3} from 'lucide-react';
import {defaults, filterJobs, ranking, csv, matchesRequirement} from './stats';
import type {Filters, Job, Snapshot} from './types';
import './style.css';

const categories = {ai:['AI / 机器学习','AI / Machine learning'],vision:['计算机视觉','Computer vision'],'3d':['3D 重建 / SLAM','3D / SLAM'],ece:['ECE 软件','ECE software']};
const levels:Record<string,string[]> = {intern:['实习','Internship'],graduate:['应届 / 初级','Graduate / Entry'],unknown:['级别未明确','Unspecified'],experienced:['有经验','Experienced']};
const requirements:Record<string,string[]> = {required:['必需','Required'],preferred:['加分','Preferred'],mentioned:['仅提及','Mentioned'],unknown:['无法判断','Uncertain']};
const safeUrl=(url:string)=>url.startsWith('https://')?url:'#';

function App(){
  const [lang,setLang]=useState<'zh'|'en'>('zh'); const en=lang==='en'; const t=(zh:string,eng:string)=>en?eng:zh;
  const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[view,setView]=useState('overview');
  const [filters,setFilters]=useState<Filters>(defaults),[selected,setSelected]=useState<Job|null>(null),[limit,setLimit]=useState(12);
  const [retry,setRetry]=useState(0);
  useEffect(()=>{const controller=new AbortController(); setError(''); fetch(`${import.meta.env.BASE_URL}data/snapshot.json`,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error(String(r.status));return r.json()}).then(d=>{if(d.schema_version!==1||!Array.isArray(d.jobs)||!Array.isArray(d.sources))throw Error('schema');setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[retry]);
  useEffect(()=>{document.documentElement.lang=en?'en':'zh-CN'},[en]);
  useEffect(()=>{setLimit(12)},[filters]);
  useEffect(()=>{if(!selected)return;const before=document.activeElement as HTMLElement; const old=document.body.style.overflow;document.body.style.overflow='hidden';const modal=document.getElementById('job-dialog')!;const close=modal.querySelector('button') as HTMLButtonElement; close.focus(); const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const items=[...modal.querySelectorAll<HTMLElement>('button, a[href], summary')];const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);before?.focus()}},[selected]);
  const set=(key:keyof Filters,value:string)=>setFilters(f=>({...f,[key]:value}));
  const jobs=useMemo(()=>filterJobs(data?.jobs??[],filters),[data,filters]);
  const ranks=useMemo(()=>ranking(jobs,filters.requirement),[jobs,filters.requirement]);
  const comparison=useMemo(()=>{const base=filterJobs(data?.jobs??[],{...filters,market:'all'});return ['US','CN'].map(m=>{const rows=base.filter(j=>j.markets.includes(m));return{market:m,total:rows.length,rank:ranking(rows,filters.requirement)}})},[data,filters]);
  const sources=data?.sources??[];const connected=sources.filter(s=>s.status==='ok').length;
  const date=(value:string|null)=>value?new Date(value).toLocaleString(en?'en-US':'zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):t('尚未更新','Not updated');
  const stale=data?.generated_at && Date.now()-Date.parse(data.generated_at)>48*3600*1000;
  const exportCsv=()=>{const a=document.createElement('a');const url=URL.createObjectURL(new Blob([csv(jobs,filters.requirement)],{type:'text/csv;charset=utf-8;'}));a.href=url;a.download='job-skill-radar.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  const navigate=(name:string)=>{setView(name);window.scrollTo({top:0,behavior:'smooth'})};
  const nav=[['overview',LayoutDashboard,t('技能概览','Overview')],['jobs',BriefcaseBusiness,t('岗位探索','Explore jobs')],['sources',Database,t('数据来源','Data sources')],['method',BookOpen,t('分析方法','Methodology')]] as const;
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('overview')}}><span className="brand-icon"><Radar size={24}/></span><span>Job Skill<span className="brand-sub">RADAR</span></span></a><div className="nav-label">WORKSPACE</div><nav aria-label={t('主导航','Main navigation')}>{nav.map(([id,Icon,label])=><button key={id} className={view===id?'nav-item active':'nav-item'} onClick={()=>navigate(id)}><Icon size={19}/><span>{label}</span>{id==='jobs'&&data&&<span className="nav-count">{data.jobs.filter(j=>j.active).length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="source-mini"><span className="pulse"/>{t('官网数据 · 每日采集','Official sources · Daily scan')}<small>{t('每一项技能，都有据可查。','Every skill, backed by evidence.')}</small></div><a className="github-link" href="https://github.com/jieera/job-skill-radar" target="_blank" rel="noreferrer"><Github size={17}/>GitHub<ArrowUpRight size={14}/></a><span className="version">OPEN SOURCE · V0.1</span></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span><strong>{nav.find(n=>n[0]===view)?.[2]}</strong></div><div className="top-actions"><span className="market-badge"><Globe2 size={14}/>{t('美国 & 中国','US & China')}</span><button className="language" onClick={()=>setLang(en?'zh':'en')} aria-label={t('Switch to English','切换中文')}>{en?'中文':'EN'}</button></div></header>
    <main><section className="page-intro"><div><div className="eyebrow"><span/>CAREER INTELLIGENCE</div><h1>{view==='overview'?t('看见岗位背后的技能。','See the skills behind the role.'):view==='jobs'?t('找到你的下一步。','Find your next step.'):view==='sources'?t('从源头，保持透明。','Transparent, from the source.'):t('让每一个结论有迹可循。','Make every insight traceable.')}</h1><p>{t('探索中美技术岗位的真实需求，为你的下一步积累方向。','Explore real hiring requirements across the US and China. Build with direction.')}</p></div><button className="export-button" onClick={exportCsv} disabled={!jobs.length}><Download size={16}/>{t('导出数据','Export data')}</button></section>
    {error?<div className="notice error"><CircleAlert size={18}/>{t('数据加载失败，请重试。','Unable to load data. Please retry.')}<button onClick={()=>setRetry(x=>x+1)}>{t('重新加载','Retry')}</button></div>:!data?<div className="loading"><Radar size={30} className="spin"/>{t('正在读取岗位数据…','Loading job data…')}</div>:<>
    {(stale||sources.some(s=>s.status==='error'||s.status==='partial'))&&<div className="notice"><CircleAlert size={17}/>{t('部分数据可能已过时，请查看各来源的最后成功时间。','Some data may be stale. Check the last successful scan for each source.')}<button onClick={()=>navigate('sources')}>{t('查看来源','View sources')}<ArrowRight size={14}/></button></div>}
    {(view==='overview'||view==='jobs')&&<>
    <section className="filters" aria-label={t('筛选岗位','Filter jobs')}><div className="filter-heading"><SlidersHorizontal size={16}/><span>{t('筛选','Filters')}</span><button onClick={()=>setFilters(defaults)}>{t('重置','Reset')}</button></div><div className="filter-controls">
      <label>{t('市场','Market')}<select value={filters.market} onChange={e=>set('market',e.target.value)}><option value="all">{t('全部市场','All markets')}</option><option value="US">{t('美国','United States')}</option><option value="CN">{t('中国','China')}</option></select></label>
      <label>{t('公司','Company')}<select value={filters.company} onChange={e=>set('company',e.target.value)}><option value="all">{t('全部公司','All companies')}</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label>{t('岗位级别','Career level')}<select value={filters.seniority} onChange={e=>set('seniority',e.target.value)}><option value="early">{t('实习与应届','Intern & Graduate')}</option>{Object.entries(levels).filter(([k])=>k!=='experienced').map(([k,v])=><option key={k} value={k}>{v[en?1:0]}</option>)}<option value="all">{t('全部（含未明确）','All incl. unspecified')}</option></select></label>
      <label>{t('技能要求','Requirement')}<select value={filters.requirement} onChange={e=>set('requirement',e.target.value)}><option value="all">{t('所有提及','All mentions')}</option>{Object.entries(requirements).map(([k,v])=><option key={k} value={k}>{v[en?1:0]}</option>)}</select></label>
    </div><div className="category-tabs" aria-label={t('岗位方向','Job category')}><button className={filters.category==='all'?'selected':''} onClick={()=>set('category','all')}>{t('全部方向','All fields')}</button>{Object.entries(categories).map(([key,value])=><button className={filters.category===key?'selected':''} key={key} onClick={()=>set('category',key)}>{value[en?1:0]}</button>)}</div></section>
    {filters.skill&&<div className="active-skill">{t('包含技能','Contains skill')}: <strong>{filters.skill}</strong><button aria-label={t('清除技能筛选','Clear skill filter')} onClick={()=>set('skill','')}><X size={14}/></button></div>}
    {view==='overview'&&<><section className="metrics"><Metric label={t('匹配岗位','Matching roles')} value={jobs.length} note={t('当前筛选范围内的在招岗位','Active roles in your selection')} icon={<BriefcaseBusiness size={19}/>}/><Metric label={t('发现技能','Skills identified')} value={ranks.length} note={t('中英别名归一化后','After bilingual normalization')} icon={<ScanLine size={19}/>}/><Metric label={t('已更新来源','Updated sources')} value={`${connected} / ${sources.length}`} note={t('其余来源状态公开可查','See status for every source')} icon={<Database size={19}/>}/><Metric label={t('最近采集','Latest scan')} value={date(data.generated_at)} note={t('每日自动检查 · 本地时间','Daily checks · Your local time')} icon={<Clock3 size={19}/>}/></section>
    <div className="charts-grid"><section className="panel ranking"><div className="panel-heading"><div><h2>{t('哪些技能更受需要？','Which skills show up most?')}</h2><p>{t('技能覆盖率 · 点击条形图查看对应岗位','Skill coverage · Select a bar to explore roles')}</p></div><span className="small-badge">TOP 10</span></div>{ranks.length?<div className="bars">{ranks.slice(0,10).map((r,i)=><button className="bar-row" key={r.name} onClick={()=>{set('skill',r.name);navigate('jobs')}} aria-label={`${r.name}: ${r.count} / ${jobs.length}`}><span className="rank-no">{String(i+1).padStart(2,'0')}</span><span className="skill-label">{r.name}</span><span className="bar-track"><span className="bar-fill" style={{width:`${r.percent}%`,opacity:1-i*.045}}/></span><strong>{r.percent.toFixed(0)}<small>%</small></strong><span className="bar-count">{r.count}</span></button>)}</div>:<Empty en={en}/>}<div className="panel-foot"><span className="dot purple"/>{t('每个岗位对同一技能只计数一次','Each skill is counted once per role')}<span>n = {jobs.length}</span></div></section>
    <section className="panel comparison"><div className="panel-heading"><div><h2>{t('跨市场，看差异','A view across markets')}</h2><p>{t('沿用其他筛选，分别计算两地覆盖率','Same filters, separate market denominators')}</p></div><Globe2 size={20} className="muted"/></div><div className="comparison-legend"><span><i className="dot purple"/>{t('美国','US')} <b>{comparison[0].total}</b></span><span><i className="dot teal"/>{t('中国','China')} <b>{comparison[1].total}</b></span></div>{[...new Set(comparison.flatMap(c=>c.rank.slice(0,5).map(r=>r.name)))].slice(0,6).map(name=><div className="compare-row" key={name}><span>{name}</span>{comparison.map(c=>{const r=c.rank.find(r=>r.name===name);return <div className="compare-bar" key={c.market}><span><i className={c.market==='US'?'purple-bg':'teal-bg'} style={{width:`${r?.percent??0}%`}}/></span><small>{c.total?`${(r?.percent??0).toFixed(0)}%`:'—'}</small></div>})}</div>)}{!comparison.some(c=>c.total>0)&&<Empty en={en}/>}<div className="sample-note">{t('样本来自已接入公司，不代表整个就业市场。','Connected-company samples, not the whole hiring market.')}</div></section></div>
    <section className="insight-strip"><span className="insight-icon"><Layers3 size={23}/></span><div><strong>{t('从技能到岗位，保留完整依据','From skills to roles, keep the evidence')}</strong><p>{t('展开岗位详情，查看技能出现的原句，以及它是必需项还是加分项。','Open a role to read the original skill evidence and its requirement level.')}</p></div><button onClick={()=>navigate('jobs')}>{t('探索岗位','Explore roles')}<ArrowRight size={17}/></button></section></>}
    <section className="panel jobs-panel"><div className="panel-heading"><div><h2>{view==='jobs'?t('岗位列表','Role explorer'):t('正在招聘','Open roles')} <span className="count-pill">{jobs.length}</span></h2><p>{t('直接来自公司官网 · 点击岗位查看技能证据','Direct from official careers pages · Open a role for evidence')}</p></div><label className="search-box"><Search size={16}/><input aria-label={t('搜索岗位、公司或技能','Search roles, companies or skills')} placeholder={t('搜索岗位、公司或技能…','Search roles or skills…')} value={filters.search} onChange={e=>set('search',e.target.value)}/></label></div><div className="job-table"><div className="table-header"><span>{t('岗位 / 公司','ROLE / COMPANY')}</span><span>{t('工作地点','LOCATION')}</span><span>{t('技能线索','SKILL SIGNALS')}</span><span/></div>{jobs.slice(0,view==='overview'?5:limit).map(job=><button className="job-row" key={job.id} onClick={()=>setSelected(job)}><span className="role-cell"><span className={`company-mark ${job.source}`}>{job.source==='nvidia'?'N':job.source==='apple'?'a':job.source==='tencent'?'T':job.company[0]}</span><span><strong>{job.title}</strong><small>{job.company}<i/> {levels[job.seniority]?.[en?1:0]??job.seniority}</small></span></span><span className="location-cell">{job.location}</span><span className="skills-cell">{job.skills.filter(s=>matchesRequirement(s,filters.requirement)).slice(0,3).map(s=><span key={s.name}>{s.name}</span>)}</span><ArrowUpRight size={17}/></button>)}</div>{!jobs.length&&<Empty en={en}/>}<div className="jobs-footer"><span>{t('数据仅供研究与求职参考，请以官网信息为准。','Research use. Always confirm details on the employer website.')}</span>{view==='overview'?<button onClick={()=>navigate('jobs')}>{t('查看全部岗位','View all roles')}<ArrowRight size={14}/></button>:jobs.length>limit&&<button onClick={()=>setLimit(n=>n+12)}>{t('加载更多','Load more')}<ChevronDown size={15}/></button>}</div></section></>}
    {view==='sources'&&<><div className="source-grid">{sources.map(s=><article className="panel source-card" key={s.id}><div className="source-title"><h2>{s.name}</h2><span className={`status ${s.status}`}>{s.status==='ok'?<Check size={13}/>:s.status==='error'?<CircleAlert size={13}/>:<Clock3 size={13}/>} {s.status==='ok'?t('已更新','Updated'):s.status==='error'?t('采集失败','Failed'):s.status==='partial'?t('部分更新','Partial'):t('待接入','Pending')}</span></div><p>{s.scope}</p><div className="source-meta"><span>{t('在招相关岗位','Active relevant roles')}<b>{s.job_count}</b></span><span>{t('最后成功','Last success')}<b>{date(s.last_success)}</b></span></div><p className="source-message">{s.message}</p><a href={safeUrl(s.url)} target="_blank" rel="noreferrer">{t('访问招聘官网','Official careers site')}<ArrowUpRight size={15}/></a></article>)}</div><div className="notice"><Clock3 size={18}/>{t('定时任务每日运行一次；GitHub 调度可能延迟。失败来源保留旧数据，连续两次完整采集未出现的职位才标记下线。','Scheduled daily; GitHub may delay runs. Failed sources retain previous data. Roles close after two complete scans miss them.')}</div></>}
    {view==='method'&&<section className="panel methodology"><div className="eyebrow">HOW IT WORKS</div><h2>{t('透明的方法，可复现的结果。','Transparent methods. Reproducible results.')}</h2>{[[t('01 · 从招聘官网开始','01 · Start at the source'),t('只采集已验证的公开职位列表与详情。公司、范围和最后成功时间公开展示；未接通的来源不参与统计。','Read verified public job lists and details. Each source shows its scope and last successful scan. Unconnected sources add no data.')],[t('02 · 中英技能归一化','02 · Normalize bilingual skills'),t('通过可编辑词典合并中英别名。技能只从描述中提取，并保留原句；不根据职位名称猜测。规则不能理解所有语义，未识别的技能可能遗漏。','An editable dictionary unifies Chinese and English aliases. Skills come from descriptions, never title-based guesses. Evidence is preserved; rules can miss unfamiliar skills and context.')],[t('03 · 区分提及和要求','03 · Separate mentions from requirements'),t('依据章节标题和句内关键词区分必需、加分、仅提及与无法判断。熟悉 Python 或 C++ 这样的替代关系仍分别计入提及，不能理解为两项都必须。','Section headings and sentence cues classify required, preferred, mentioned and uncertain evidence. Alternatives such as Python or C++ count as separate mentions, not two mandatory requirements.')],[t('04 · 明确统计分母','04 · Define the denominator'),t('覆盖率 = 包含该技能的去重岗位数 ÷ 当前筛选范围内的在招岗位数。技能要求筛选只改变分子。跨市场图忽略市场筛选，分别计算两地分母；多地岗位可在两地各计一次。','Coverage = unique roles mentioning a skill / all active roles in the selection. Requirement filtering changes the numerator only. Comparison ignores the market filter and uses separate denominators. Multi-market roles may appear in both markets.')],[t('05 · 保留不确定性','05 · Keep uncertainty visible'),t('默认只看实习与应届；级别不明确的岗位需主动选择。官网时间缺失时不猜测发布日期。样本受公司覆盖范围和季节影响，不能推广为整个市场需求。','Default filters include internships and graduate roles. Unspecified levels require opt-in. Missing publication dates remain unknown. Company coverage and seasonality limit market-wide conclusions.')],[t('06 · 验证状态','06 · Evaluation status'),t('仓库提供独立测试、可复现评估脚本和人工审阅模板。任何代理标注或合成测试结果均不等同于人工验证的真实岗位准确率。','The repository includes independent tests, reproducible evaluation and a human review template. Agent labels or synthetic tests are not human-validated real-job accuracy.')]].map(([title,body])=><div className="method-step" key={title}><h3>{title}</h3><p>{body}</p></div>)}</section>}
    </>}
    <footer className="page-footer"><span><Radar size={15}/>Job Skill Radar</span><span>{t('用真实需求，为成长导航。','Real requirements. Clearer direction.')}</span><span>US / CN · {t('实习与应届','Early careers')}</span></footer></main></div>
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section id="job-dialog" className="job-dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onClick={e=>e.stopPropagation()}><div className="dialog-top"><span className="eyebrow">ROLE INTELLIGENCE</span><button aria-label={t('关闭详情','Close details')} onClick={()=>setSelected(null)}><X size={21}/></button></div><div className="dialog-company">{selected.company} · {levels[selected.seniority]?.[en?1:0]}</div><h2 id="dialog-title">{selected.title}</h2><p className="muted">{selected.location}</p><a className="official-button" href={safeUrl(selected.url)} target="_blank" rel="noreferrer">{t('查看官网岗位','View official posting')}<ArrowUpRight size={16}/></a><div className="dialog-dates"><span>{t('首次发现','First seen')}: {date(selected.first_seen)}</span><span>{t('最后核验','Last seen')}: {date(selected.last_seen)}</span></div><h3>{t('技能与原文证据','Skills & original evidence')} <span className="count-pill">{selected.skills.length}</span></h3><p className="evidence-note">{t('原文保留原语言；“或”表示替代选项，不代表所有技能都必须具备。','Original language retained. “Or” indicates alternatives, not a requirement for every listed skill.')}</p>{selected.skills.length?selected.skills.map(skill=><details className="evidence" key={skill.name} open={skill.name===filters.skill}><summary><strong>{skill.name}</strong><span>{[...new Set(skill.evidence.map(e=>e.requirement))].map(r=><i className={`requirement ${r}`} key={r}>{requirements[r][en?1:0]}</i>)}</span><ChevronDown size={14}/></summary>{skill.evidence.map((e,i)=><div className="quote" key={i}><span className={`requirement ${e.requirement}`}>{requirements[e.requirement][en?1:0]}</span><blockquote>{e.text}</blockquote></div>)}</details>):<Empty en={en}/>}</section></div>}
  </div>
}
function Metric({label,value,note,icon}:{label:string;value:string|number;note:string;icon:React.ReactNode}){return <article className="metric"><div>{label}<span>{icon}</span></div><strong>{value}</strong><small>{note}</small></article>}
function Empty({en}:{en:boolean}){return <div className="empty"><Search size={25}/><strong>{en?'No matching results':'暂无匹配结果'}</strong><p>{en?'Try broader filters or check source availability.':'试着放宽筛选条件，或查看数据源接入状态。'}</p></div>}
createRoot(document.getElementById('root')!).render(<App/>);
